// CSS custom properties. Aliases become var(--ref) (order-independent in CSS),
// so the four-layer chain is preserved and re-themeable.
import { sortTokens, varName, cssValue, LAYER_KEY_ORDER } from "./_shared.js";

const LAYER_LABEL = {
  primitives: "Primitives",
  globalAlias: "Global Alias",
  systemAlias: "System Alias",
  component: "Component",
};

export function exportCss(tokens) {
  const sorted = sortTokens(tokens);
  const lines = [];
  lines.push("/* IQM Design System — CSS custom properties");
  lines.push(" * Generated by iqm-ds-sync (Phase 7). Do not edit by hand.");
  lines.push(` * ${sorted.length} tokens. Aliases use var(--ref) to preserve the four-layer chain.`);
  lines.push(" *");
  lines.push(" * NOTE: dimension tokens are emitted as unitless numbers (the store holds raw");
  lines.push(" * Figma values); apply units at the use site. Per-mode (Light/Dark) values are");
  lines.push(" * not yet captured upstream — each token carries its default-mode value only.");
  lines.push(" */");
  lines.push(":root {");

  let currentLayer = null;
  for (const t of sorted) {
    const layerKey = t.tokenPath.split("/")[0];
    if (layerKey !== currentLayer) {
      currentLayer = layerKey;
      lines.push(`\n  /* ${LAYER_LABEL[layerKey] || layerKey} */`);
    }
    const desc = t.$description ? `  /* ${String(t.$description).replace(/\*\//g, "*\\/").slice(0, 120)} */` : "";
    lines.push(`  --${varName(t.tokenPath)}: ${cssValue(t)};${desc}`);
  }

  lines.push("}");
  return lines.join("\n") + "\n";
}
