// ES module — the nested DTCG tree plus small runtime helpers. Pairs with
// tokens.d.ts for typed access.
import { nestTokens, sortTokens, dottedPath } from "./_shared.js";

export function exportJavascript(tokens) {
  const tree = nestTokens(tokens, { coerce: true });
  const paths = sortTokens(tokens).map((t) => dottedPath(t.tokenPath));

  const lines = [];
  lines.push("// IQM Design System — token ES module");
  lines.push("// Generated by iqm-ds-sync (Phase 7). Do not edit by hand.");
  lines.push("// @typedef {{ $value: string|number|boolean|null, $type: string, $description: string|null, $extensions: object|null }} Token");
  lines.push("");
  lines.push(`export const tokens = ${JSON.stringify(tree, null, 2)};`);
  lines.push("");
  lines.push(`export const tokenPaths = ${JSON.stringify(paths, null, 2)};`);
  lines.push("");
  lines.push("// getToken('globalAlias.primary-600') -> the token's $value (or undefined).");
  lines.push("export function getToken(path) {");
  lines.push("  let node = tokens;");
  lines.push("  for (const seg of String(path).split('.')) {");
  lines.push("    if (node == null || typeof node !== 'object') return undefined;");
  lines.push("    node = node[seg];");
  lines.push("  }");
  lines.push("  return node && typeof node === 'object' && '$value' in node ? node.$value : undefined;");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}
