// SCSS variables. Unlike CSS custom properties, SCSS `$vars` are resolved at
// compile time and are order-dependent, so aliases are flattened to their
// concrete value (following the chain) to guarantee valid, order-safe output.
import { sortTokens, varName, byDottedMap, resolveConcrete, LAYER_KEY_ORDER } from "./_shared.js";

const LAYER_LABEL = {
  primitives: "Primitives",
  globalAlias: "Global Alias",
  systemAlias: "System Alias",
  component: "Component",
};

function scssScalar(v) {
  if (v == null) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  // Quote strings that aren't already safe bare tokens (hex, cubic-bezier, etc. are fine bare).
  return String(v);
}

export function exportScss(tokens) {
  const sorted = sortTokens(tokens);
  const byDotted = byDottedMap(tokens);
  const lines = [];
  lines.push("// IQM Design System — SCSS variables");
  lines.push("// Generated by iqm-ds-sync (Phase 7). Do not edit by hand.");
  lines.push(`// ${sorted.length} tokens. Aliases are flattened to concrete values`);
  lines.push("// (SCSS variables are order-dependent, unlike CSS custom properties).");
  lines.push("");

  let currentLayer = null;
  const mapEntries = [];
  for (const t of sorted) {
    const layerKey = t.tokenPath.split("/")[0];
    if (layerKey !== currentLayer) {
      currentLayer = layerKey;
      lines.push(`\n// ${LAYER_LABEL[layerKey] || layerKey}`);
    }
    const name = varName(t.tokenPath);
    const value = scssScalar(resolveConcrete(t, byDotted));
    lines.push(`$${name}: ${value};`);
    mapEntries.push(`  "${t.tokenPath}": $${name},`);
  }

  // A lookup map for programmatic access: map-get($iqm-tokens, "globalAlias/primary-600")
  lines.push("\n// Lookup map — map-get($iqm-tokens, \"globalAlias/primary-600\")");
  lines.push("$iqm-tokens: (");
  lines.push(...mapEntries);
  lines.push(");");

  return lines.join("\n") + "\n";
}
