// TypeScript declarations that pair with tokens.js — a TokenPath union of every
// dotted path (autocomplete in editors) plus typed `tokens` / `getToken`.
import { sortTokens, dottedPath } from "./_shared.js";

export function exportTypescript(tokens) {
  const paths = sortTokens(tokens).map((t) => dottedPath(t.tokenPath));
  const union = paths.map((p) => `  | ${JSON.stringify(p)}`).join("\n");

  const lines = [];
  lines.push("// IQM Design System — token type definitions");
  lines.push("// Generated by iqm-ds-sync (Phase 7). Do not edit by hand.");
  lines.push("// Pairs with tokens.js (same directory).");
  lines.push("");
  lines.push("export interface Token {");
  lines.push("  $value: string | number | boolean | null;");
  lines.push("  $type: string;");
  lines.push("  $description: string | null;");
  lines.push("  $extensions: Record<string, unknown> | null;");
  lines.push("}");
  lines.push("");
  lines.push("/** Every valid dotted token path. */");
  lines.push("export type TokenPath =");
  lines.push(`${union};`);
  lines.push("");
  lines.push("/** Nested DTCG token tree (layer -> ... -> Token). */");
  lines.push("export declare const tokens: Record<string, unknown>;");
  lines.push("");
  lines.push("/** All token paths, in export order. */");
  lines.push("export declare const tokenPaths: readonly TokenPath[];");
  lines.push("");
  lines.push("/** Resolve a token path to its $value. */");
  lines.push("export declare function getToken(path: TokenPath): string | number | boolean | null | undefined;");
  lines.push("");
  return lines.join("\n");
}
